polar:
  greeting: 欢迎来到book catalog（minikube）！
  spring:
    datasource:
      url: jdbc:postgresql://polar-postgres/polardb_catalog
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://polar-keycloak/realms/PolarBookshop
