apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  labels:
    app: catalog-service
data:
  # 会覆盖应用application.yml中的配置
  application.yml: |
    polar:
      greeting: 欢迎来到book catalog（K8s）！
    spring:
      datasource:
        url: jdbc:postgresql://polar-postgres/polardb_catalog
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://polar-keycloak/realms/PolarBookshop
