apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    # Kustomization要管理的K8s清单
  - deployment.yml
  - service.yml

# 替代configmap.yml方式管理ConfigMap
configMapGenerator:
  - name: catalog-config
    files:
        # 使用属性文件作为ConfigMaps的源
      - application.yml
    options:
      labels:
        # 定义分配给所生成ConfigMap的标签
        app: catalog-service
