# 工作流的名称
name: Commit Stage
# 触发时机
on: push

jobs:
  # job的唯一标识符
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      # 检出当前git仓库的权限
      contents: read
      # 提交安全事件至github的权限
      security-events: write
    steps:
      - name: "检查源码"
        uses: actions/checkout@v3
      - name: "安装JDK"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: "代码漏洞扫描"
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{github.workspace}}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true
      - name: "上传漏洞报告"
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{steps.scan.outputs.sarif}}
      - name: "构建，单元测试和集成测试"
        run: |
          chmod +x gradlew
          ./gradlew build
